name: deploy-function

on: 
  push:
    branches: [main]

env: 
  function_name: hello

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: auth
        name: google auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.SERVICE_ACCOUNT_JSON }}
      - id: 'deploy'
        name: deploy cloud function
        uses: 'google-github-actions/deploy-cloud-functions@v0'
        with:
          name: ${{ env.function_name }}
          runtime: 'python39'
          service_account_email: functions@macro-gadget-348914.iam.gserviceaccount.com
          source_dir: ${{ env.function_name }}
      - name: 'call deployed function'
        run: 'curl "${{ steps.deploy.outputs.url }}"'
