name: Tests

on: [pull_request, workflow_dispatch]

env:
    FUNCTION_NAME: hello

jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Setup Python
              uses: actions/setup-python@v2
              with:
                python-version: 3.9
            - name: Install dependencies
              run: |
               pip install -r requirements-dev.txt
               pip install -r $FUNCTION_NAME/requirements.txt
            - name: Test
              run: |
               coverage run -m pytest -v $FUNCTION_NAME/main_test.py
               coverage report $FUNCTION_NAME/main.py
